INSERT INTO users (name, age) VALUES ("randy", 30);
INSERT INTO users (name, age) VALUES ("beth", 30);
INSERT INTO users (name, age) VALUES ("lady", 30);
INSERT INTO users (name, age) VALUES ("james", 30);
INSERT INTO users (name, age) VALUES ("eva", 30);
INSERT INTO users (name, age) VALUES ("kevin", 30);
INSERT INTO users (name, age) VALUES ("kevin", 30);
INSERT INTO users (name, age) VALUES ("rahman", 30);
INSERT INTO users (name, age) VALUES ("luke", 30);
INSERT INTO users (name, age) VALUES ("jaclyn", 30);
INSERT INTO users (name, age) VALUES ("fay", 30);
INSERT INTO users (name, age) VALUES ("luke", 30);
INSERT INTO users (name, age) VALUES ("ogulcan", 30);
INSERT INTO users (name, age) VALUES ("annabel", 30);
INSERT INTO users (name, age) VALUES ("katie", 30);
INSERT INTO users (name, age) VALUES ("brendan", 30);
INSERT INTO users (name, age) VALUES ("brandon", 30);
INSERT INTO users (name, age) VALUES ("jinook", 30);
INSERT INTO users (name, age) VALUES ("katie", 30);
INSERT INTO users (name, age) VALUES ("laura", 30);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ( "checkers", "board games", 1, "01/12/92", "01/13/94");

INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 1, 4);